### ISSUE TITLE
how to spawn an child actor

### ISSUE THREAD

**Issue by wushanchao** [akka-js/akka.js_bindings#2]
```javascript
const akkajs = require("akkajs")

const system = akkajs.ActorSystem.create()


class PingerChild extends akkajs.Actor {
    constructor() {
        super()
        this.name = "PingerChild"
        this.receive = this.receive.bind(this)
    }
    receive(msg) {
        console.log("RECEIVED PingerChild", msg)
        this.sender().tell("pong")
    }
}

const pingerChild = system.spawn(new PingerChild())

class Pinger extends akkajs.Actor {
    constructor() {
        super()
        this.name = "pinger"
        this.receive = this.receive.bind(this)
        this.spawn(pingerChild)
    }
    receive(msg) {
        console.log("RECEIVED PING", msg)
        this.sender().tell("pong")
    }
}

const pinger = system.spawn(new Pinger())

class Ponger extends akkajs.Actor {
    constructor() {
        super()
        this.name = "ponger"
        this.receive = this.receive.bind(this)
    }
    receive(msg) {
        console.log("RECEIVED PONG", msg)
        // this.sender().tell("ping")
    }
}



const ponger = system.spawn(new Ponger())

pinger.tell("ping", ponger)
```

throw error msg
```
function yd(a){if(null===a)throw(new zd).a("actor name must not be null");if(""===a)throw(new zd).a("actor name must not be empty");Ad||(Ad=(new Bd).c());var b;if(null===a)throw(new fc).c();if(""===a)b=-2;else if(b=a.length|0,0<b&&36!==(65535&(a.charCodeAt(0)|0)))b:{var d=0;for(;;)if(d<b){var e=65535&(a.charCodeAt(d)|0),f=e;if(97<=f&&122>=f||65<=f&&90>=f||48<=f&&57>=f||-1!==Cd(Da(),"-_.*$+:@\x26\x3d,!~';",f))d=1+d|0;else if(37===e&&(2+d|0)<b&&Dd(65535&(a.charCodeAt(1+d|0)|0))&&Dd(65535&(a.charCodeAt(2+

                                                            ^

TypeError: Cannot read property 'length' of undefined
    at yd (C:\Users\Documents\test\affka\node_modules\_akkajs@1.0.1@akkajs\lib\akkajs.js:27:218)
    at Fd (C:\Users\Documents\test\affka\node_modules\_akkajs@1.0.1@akkajs\lib\akkajs.js:29:78)
    at nH (C:\Users\Documents\test\affka\node_modules\_akkajs@1.0.1@akkajs\lib\akkajs.js:680:136)
    at Pinger.ba.Actor.a.spawn (C:\Users\Documents\test\affka\node_modules\_akkajs@1.0.1@akkajs\lib\akkajs.js:1991:194)
    at new Pinger (C:\Users\Documents\test\affka\index.js:25:14)
    at Object.<anonymous> (C:\Users\Documents\test\affka\index.js:33:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by wushanchao** [comment]
```javascript
const akkajs = require("akkajs")

const system = akkajs.ActorSystem.create()


class PingerChild extends akkajs.Actor {
    constructor() {
        super()
        this.name = "PingerChild"
        this.receive = this.receive.bind(this)
    }
    receive(msg) {
        console.log("RECEIVED PingerChild", msg)
        this.sender().tell("pong")
    }
}

// const pingerChild = system.spawn(new PingerChild())

class Pinger extends akkajs.Actor {
    constructor() {
        super()
        this.name = "pinger"
        this.receive = this.receive.bind(this)
        
    }
    preStart(){
        this.spawn(new PingerChild())
    }
    receive(msg) {
        console.log("RECEIVED PING", msg)
        this.sender().tell("pong")
    }
}

const pinger = system.spawn(new Pinger())

class Ponger extends akkajs.Actor {
    constructor() {
        super()
        this.name = "ponger"
        this.receive = this.receive.bind(this)
    }
    receive(msg) {
        console.log("RECEIVED PONG", msg)
        // this.sender().tell("ping")
    }
}



const ponger = system.spawn(new Ponger())

pinger.tell("ping", ponger)

```

**Comment by andreaTP** [comment]
Correct,. thanks for posting also the solution.
Basically the `spawn` method is available in `preStart` and `receive` but not in the constructor, and the Actor to be created should be spawned "in-place".
